config:
  target: 'http://localhost:3333/'
  phases:
  - duration: 60
  arrivalRate: 20
  name: Load Test
  defaults:
    headers:
      x-my-service-auth: '987401838271002188298567'
scenarios:
- flow:
- get:
url: "/"